#!/usr/bin/env python3
"""STATUS: PROPOSED — 2026-09-06 — produced by the AI collaborator; not
adopted; the commit is the author's.

PROBE — NON-DISCHARGING. Generates the companion modules from the correct
module by exact substitution at the three MUTATION SITE lines, so that
`diff P10_ManifestAuthority.tla P10_ManifestAuthority_<X>.tla` is the
header plus exactly the mutation. Re-run to regenerate; never edit the
generated files by hand. Not service code (design-probe tier item 2).
ADDED 2026-09-06 (same day, later): a fourth substitution site, the Init
waiver line, for the A121Literal reading variant (RESULTS-PROBE.md O1, made
reproducible instead of scratch).
CORRECTED 2026-09-06 (later still): the BrokenAnchorIgnored banner had attributed
LaterCaptureStrictUnreachable to the frozen Q6 prediction; it was a build-time
addition (PROBE.md post-run note 3 item 1). Comment text only; no mutation changed."""
import pathlib, re, sys

HERE = pathlib.Path(__file__).resolve().parent
SRC = (HERE / "P10_ManifestAuthority.tla").read_text()

HEAD_RE = re.compile(r"^-+ MODULE P10_ManifestAuthority -+\n", re.M)
OBSERVE_LATE = '  ELSE IF ev[ch].anchor = "late"       THEN "anchor_late"   \\* MUTATION SITE: AnchorIgnored\n'
VERDICT = 'VerdictHere == P4!Verdict                              \\* MUTATION SITE: SelfCounted, AnyOne\n'
RECORD = ('RecordHere ==                                          \\* MUTATION SITE: Silent\n'
          '  IF VerdictHere = "VALID_DEGRADED"\n'
          '    THEN [policy |-> waived, why |-> [ch \\in waived |-> Observe(ch)]]\n'
          '    ELSE NoRecord\n')
INIT_WAIVED = '  /\\ waived \\in (SUBSET Channels) \\ {Channels}   \\* A3.2 item 1: fewer, never zero (I4: fixed before the bundle)\n'
for needle in (OBSERVE_LATE, VERDICT, RECORD, INIT_WAIVED):
    assert SRC.count(needle) == 1, needle

def banner(name, lines):
    body = "\n".join("(* " + l.ljust(71) + " *)" for l in lines)
    return (f"{'-' * 20} MODULE P10_ManifestAuthority_{name} {'-' * 20}\n"
            "(***************************************************************************)\n"
            "(* STATUS: PROPOSED — 2026-09-06 — produced by the AI collaborator; not   *)\n"
            "(* adopted; the commit is the author's. PROBE — NON-DISCHARGING.           *)\n"
            "(* GENERATED by make-companions.py from P10_ManifestAuthority.tla; the    *)\n"
            "(* body below is the correct module with exactly one marked mutation.     *)\n"
            f"{body}\n"
            "(***************************************************************************)\n")

COMPANIONS = {
    "BrokenSilent": dict(
        lines=["DELIBERATELY BROKEN — degrades SILENTLY: the verdict is P4's, the",
               "record is empty. P10: 'naming which authority evidence was waived",
               "and why — never silently'. Predicted red (PROBE.md Q6):",
               "{DegradedNamesWaived, NeverSilent}."],
        subs=[(RECORD, 'RecordHere == NoRecord                                 \\* BROKEN: no record, ever\n')]),
    "BrokenSelfCounted": dict(
        lines=["DELIBERATELY BROKEN — the A1.5 circularity: the manifest self-",
               "signature is counted as a third authority channel and VALID_STRICT",
               "requires any two of the three to validate. Predicted red (PROBE.md",
               "Q6): {StrictNeedsAuthorizedKey, StrictMeansBothAgree}."],
        subs=[(VERDICT,
               'VerdictHere ==                                         \\* BROKEN: self-signature counted as a channel\n'
               '  IF /\\ waived = {}\n'
               '     /\\ Cardinality({ch \\in Channels : ChanStatus(ch) = "pass"}\n'
               '                    \\cup (IF poss = "pass" THEN {"self"} ELSE {})) >= 2\n'
               '    THEN "VALID_STRICT"\n'
               '    ELSE P4!Verdict\n')]),
    "BrokenAnchorIgnored": dict(
        lines=["DELIBERATELY BROKEN — the verifier never checks the evidence's own",
               "anchor time: a late-anchored evidence is observed as if it were in",
               "the window. The 2106 attack: both channels captured AFTER the window",
               "(compIssue = {}, compLater = Channels), fresh evidences naming kA.",
               "Predicted red (PROBE.md Q6, frozen): {StrictNeedsAuthorizedKey};",
               "StrictMeansBothAgree joins (p~0.85). LaterCaptureStrictUnreachable",
               "was added at build time, unfrozen (PROBE.md post-run note 3 item 1)."],
        subs=[(OBSERVE_LATE, '  \\* BROKEN: anchor-time check removed (was: ELSE IF ev[ch].anchor = "late" THEN "anchor_late")\n')]),
    "BrokenAnyOne": dict(
        lines=["DELIBERATELY BROKEN — 'at least one' instead of 'both' (the misreading",
               "the Haiku reader made of first-link Q3, READING-AID-Q3.md): VALID_STRICT",
               "when either external evidence validates. Predicted red (PROBE.md Q6):",
               "{StrictNeedsAuthorizedKey, StrictMeansBothAgree, NeverSilent}."],
        subs=[(VERDICT,
               'VerdictHere ==                                         \\* BROKEN: any one channel suffices for strict\n'
               '  IF waived = {} /\\ poss = "pass" /\\ \\E ch \\in Channels : ChanStatus(ch) = "pass"\n'
               '    THEN "VALID_STRICT"\n'
               '    ELSE P4!Verdict\n')]),
    "A121Literal": dict(
        lines=["READING VARIANT, not a companion (PROBE.md post-run note 2; RESULTS",
               "O1): A1.2.1's own words — 'accepting fewer than all external",
               "manifest-authority evidences' — WITHOUT A3 §A3.2 item 1's tightening",
               "('fewer, but never zero'): Init admits waived = Channels. Elsewhere",
               "identical to the correct module. Predicted red: {NeverZero,",
               "UnavailabilityIsNotWaiver, PossessionNeverAuthority}; predicted green:",
               "StrictNeedsAuthorizedKey, DegradedNamesWaived and the rest."],
        subs=[(INIT_WAIVED,
               '  /\\ waived \\in SUBSET Channels                  \\* READING: A1.2.1 literal, A3.2 item 1 NOT applied — zero admitted\n')]),
    "A32Reading": dict(
        lines=["READING VARIANT, not a companion (PROBE.md Q3): A3 §A3.2 item 2's",
               "second sentence read literally — 'Evidence that is present and whose",
               "validation is performed but fails yields INVALID' — applied to EVERY",
               "channel evidence, waived or not. Elsewhere identical to the correct",
               "module (P4's verdict). Predicted: all main invariants green AND",
               "DegradedWaivedFailUnreachable holds as an invariant."],
        subs=[(VERDICT,
               'VerdictHere ==                                         \\* A3.2 item 2, literal reading\n'
               '  IF \\E ch \\in Channels : ChanStatus(ch) = "fail"\n'
               '    THEN "INVALID"\n'
               '    ELSE P4!Verdict\n')]),
}

for name, spec in COMPANIONS.items():
    text = SRC
    # replace the module line and the whole leading comment block with the banner
    m = HEAD_RE.search(text); assert m and m.start() == 0
    end = text.index("EXTENDS FiniteSets")
    text = banner(name, spec["lines"]) + text[end:]
    for old, new in spec["subs"]:
        assert text.count(old) == 1, (name, old)
        text = text.replace(old, new)
    (HERE / f"P10_ManifestAuthority_{name}.tla").write_text(text)
    print("wrote", name)
