-------------------- MODULE P10_ManifestAuthority_BrokenAnchorIgnored --------------------
(***************************************************************************)
(* STATUS: PROPOSED — 2026-09-06 — produced by the AI collaborator; not   *)
(* adopted; the commit is the author's. PROBE — NON-DISCHARGING.           *)
(* GENERATED by make-companions.py from P10_ManifestAuthority.tla; the    *)
(* body below is the correct module with exactly one marked mutation.     *)
(* DELIBERATELY BROKEN — the verifier never checks the evidence's own      *)
(* anchor time: a late-anchored evidence is observed as if it were in      *)
(* the window. The 2106 attack: both channels captured AFTER the window    *)
(* (compIssue = {}, compLater = Channels), fresh evidences naming kA.      *)
(* Predicted red (PROBE.md Q6, frozen): {StrictNeedsAuthorizedKey};        *)
(* StrictMeansBothAgree joins (p~0.85). LaterCaptureStrictUnreachable      *)
(* was added at build time, unfrozen (PROBE.md post-run note 3 item 1).    *)
(***************************************************************************)
EXTENDS FiniteSets, Naturals

Channels  == {"dns", "repo"}
Keys      == {"kH", "kA"}          \* honest (authorized) key; adversary's key
Authorized == {"kH"}               \* ground truth: what an honest channel publishes
Sigs      == {"valid", "invalid", "unperformable"}
Anchors   == {"consistent", "late"}
Checks    == Channels \cup {"poss"}

(* An archived evidence in the bundle, or Absent (one canonical record with   *)
(* present = FALSE; RECUT 1: TLC will not compare a record with a string).     *)
EvRecords == [present: {TRUE}, names: Keys, sig: Sigs, anchor: Anchors]
Absent    == [present |-> FALSE, names |-> "kH", sig |-> "valid", anchor |-> "consistent"]
Evidences == EvRecords \cup {Absent}

Observations == {"absent", "unperformable", "invalid", "anchor_late",
                 "names_other_key", "would_pass"}

VARIABLES
  phase,      \* "setup" -> "published" -> "presented" -> "verified"
  compIssue,  \* channels the adversary controls at issue time (A1.3 item 6)
  compLater,  \* channels it comes to control after the issuance window
  ev,         \* [Channels -> Evidences]: what the bundle carries per channel
  mkey,       \* the key the presented manifest asserts
  poss,       \* self-signature under mkey over the manifest: "pass" | "fail"
  waived,     \* the verifier's declared policy: waived channel checks
  verdict,    \* P4's verdict, or "none" before verification
  record      \* the VALID_DEGRADED record: [policy, why]

vars == <<phase, compIssue, compLater, ev, mkey, poss, waived, verdict, record>>

NoRecord == [policy |-> {}, why |-> [ch \in {} |-> "absent"]]

(***************************************************************************)
(* What each channel can put in the bundle (Publish). The honest branch   *)
(* is always available: the bundle may carry the honest evidence intact,  *)
(* with altered bytes (A1.3 item 1 -> "invalid"), with an unrecoverable   *)
(* historical trust anchor (A1.5 recursion -> "unperformable"), or not at *)
(* all (stripped, or the channel lapsed -> "absent"). The adversary        *)
(* branches are gated by I1/I2 above.                                      *)
(***************************************************************************)
HonestEv(ch) ==
  {[present |-> TRUE, names |-> "kH", sig |-> s, anchor |-> "consistent"] : s \in Sigs}

AtIssueEv(ch) ==
  IF ch \in compIssue THEN EvRecords ELSE {}

LaterEv(ch) ==
  IF ch \in compLater \ compIssue
    THEN {[present |-> TRUE, names |-> k, sig |-> s, anchor |-> "late"] : k \in Keys, s \in Sigs}
    ELSE {}

Producible(ch) == HonestEv(ch) \cup AtIssueEv(ch) \cup LaterEv(ch) \cup {Absent}

(***************************************************************************)
(* Observation and classification (Verify). The observation is the six-   *)
(* valued "why" that the record carries; the status is P4's three-valued  *)
(* shared term.                                                            *)
(***************************************************************************)
Observe(ch) ==
  IF ~ev[ch].present                   THEN "absent"
  ELSE IF ev[ch].sig = "unperformable" THEN "unperformable"
  ELSE IF ev[ch].sig = "invalid"       THEN "invalid"
  \* BROKEN: anchor-time check removed (was: ELSE IF ev[ch].anchor = "late" THEN "anchor_late")
  ELSE IF ev[ch].names # mkey          THEN "names_other_key"
  ELSE "would_pass"

ChanStatus(ch) ==
  CASE Observe(ch) \in {"absent", "unperformable"}                  -> "unperformable"
    [] Observe(ch) \in {"invalid", "anchor_late", "names_other_key"} -> "fail"
    [] OTHER                                                          -> "pass"

status == [c \in Checks |-> IF c = "poss" THEN poss ELSE ChanStatus(c)]

(* THE JOIN: P4's verdict function over the shared status map. *)
P4 == INSTANCE P4_VerifierStates
        WITH Checks <- Checks, NonWaivable <- {"poss"},
             status <- status, waived <- waived

VerdictHere == P4!Verdict                              \* MUTATION SITE: SelfCounted, AnyOne

RecordHere ==                                          \* MUTATION SITE: Silent
  IF VerdictHere = "VALID_DEGRADED"
    THEN [policy |-> waived, why |-> [ch \in waived |-> Observe(ch)]]
    ELSE NoRecord

(***************************************************************************)
(* The state machine.                                                      *)
(***************************************************************************)
Init ==
  /\ phase = "setup"
  /\ compIssue \in SUBSET Channels
  /\ compLater \in SUBSET Channels
  /\ ev = [ch \in Channels |-> Absent]
  /\ mkey = "kH"
  /\ poss = "pass"
  /\ waived \in (SUBSET Channels) \ {Channels}   \* A3.2 item 1: fewer, never zero (I4: fixed before the bundle)
  /\ verdict = "none"
  /\ record = NoRecord

Publish ==
  /\ phase = "setup"
  /\ ev' \in {f \in [Channels -> Evidences] : \A ch \in Channels : f[ch] \in Producible(ch)}
  /\ phase' = "published"
  /\ UNCHANGED <<compIssue, compLater, mkey, poss, waived, verdict, record>>

Present ==
  /\ phase = "published"
  /\ mkey' \in Keys
  /\ poss' \in {"pass", "fail"}
  /\ phase' = "presented"
  /\ UNCHANGED <<compIssue, compLater, ev, waived, verdict, record>>

Verify ==
  /\ phase = "presented"
  /\ verdict' = VerdictHere
  /\ record' = RecordHere
  /\ phase' = "verified"
  /\ UNCHANGED <<compIssue, compLater, ev, mkey, poss, waived>>

Done == phase = "verified" /\ UNCHANGED vars

Next == Publish \/ Present \/ Verify \/ Done

Spec == Init /\ [][Next]_vars

(***************************************************************************)
(* Invariants (evaluated once verified). Each names the registered clause. *)
(***************************************************************************)
V == phase = "verified"
ValidVerdicts == {"VALID_STRICT", "VALID_DEGRADED"}

TypeOK ==
  /\ ev \in [Channels -> Evidences]
  /\ mkey \in Keys
  /\ poss \in {"pass", "fail"}
  /\ waived \in SUBSET Channels
  /\ verdict \in P4!Verdicts \cup {"none"}

(* P4: the four states partition all outcomes. *)
Partition == V => verdict \in P4!Verdicts

(* P10 (A1 lines 296-299), the headline: any PROPER subset of channels     *)
(* controlled at issue time — with NO guard on later capture — and a       *)
(* manifest asserting a non-authorized key never reaches VALID_STRICT.     *)
StrictNeedsAuthorizedKey ==
  (V /\ compIssue # Channels /\ verdict = "VALID_STRICT") => mkey \in Authorized

(* P10 / A1.5: VALID_STRICT = both external evidences validate, anchored   *)
(* in the window, naming the asserted key, plus possession, nothing waived.*)
StrictMeansBothAgree ==
  (V /\ verdict = "VALID_STRICT") =>
    /\ \A ch \in Channels : Observe(ch) = "would_pass"
    /\ poss = "pass"
    /\ waived = {}

(* P10 degraded half / A1.2.1 recording: the record names the policy that *)
(* authorized the waiver, the precise waived set, and per waived evidence  *)
(* what was observed — "why".                                              *)
DegradedNamesWaived ==
  (V /\ verdict = "VALID_DEGRADED") =>
    /\ record.policy = waived
    /\ waived # {}
    /\ DOMAIN record.why = waived
    /\ \A ch \in waived : record.why[ch] = Observe(ch)

(* "never silently": under any VALID verdict, a channel evidence that did  *)
(* not validate is in the record's waived set.                             *)
NeverSilent ==
  (V /\ verdict \in ValidVerdicts) =>
    \A ch \in Channels : ChanStatus(ch) # "pass" => ch \in record.policy

(* A3.2 item 1 (never zero) + the chain's first link: a VALID_DEGRADED     *)
(* verdict rests on an un-waived channel that validates and names mkey.    *)
NeverZero ==
  (V /\ verdict = "VALID_DEGRADED") =>
    \E ch \in Channels \ waived : ChanStatus(ch) = "pass" /\ ev[ch].names = mkey

(* A3.2 item 2: unavailability is not waiver — every channel unperformable *)
(* yields no VALID state.                                                  *)
UnavailabilityIsNotWaiver ==
  (V /\ \A ch \in Channels : ChanStatus(ch) = "unperformable") => verdict \notin ValidVerdicts

(* A1.5 item 3 / A3.2 item 3: a VALID verdict never rests on the self-     *)
(* signature alone — some un-waived external evidence validates.           *)
PossessionNeverAuthority ==
  (V /\ verdict \in ValidVerdicts) => \E ch \in Channels \ waived : ChanStatus(ch) = "pass"

(***************************************************************************)
(* Sanity witnesses — _Sanity cfg only, TLC -continue; VIOLATED is the     *)
(* healthy result (each exhibits a reachable state).                       *)
(***************************************************************************)
VerdictNeverStrict       == ~(V /\ verdict = "VALID_STRICT")
VerdictNeverDegraded     == ~(V /\ verdict = "VALID_DEGRADED")
VerdictNeverInvalid      == ~(V /\ verdict = "INVALID")
VerdictNeverUnverifiable == ~(V /\ verdict = "UNVERIFIABLE")

(* The registered waiver cost (first-link Q5b; S-P3 F8 ruling): degraded, *)
(* sole remaining channel compromised, adversary's key accepted.           *)
DegradedNonAuthorizedUnreachable == ~(V /\ verdict = "VALID_DEGRADED" /\ mkey \notin Authorized)

(* The A1.5 boundary: its trace must show compIssue = Channels.            *)
StrictNonAuthorizedUnreachable == ~(V /\ verdict = "VALID_STRICT" /\ mkey \notin Authorized)

LateEvidenceUnreachable == ~(V /\ \E ch \in Channels : Observe(ch) = "anchor_late")

(* The naming lattice is fully exercised: each observation appears in some *)
(* VALID_DEGRADED record.                                                  *)
WhyNever(o) == ~(V /\ verdict = "VALID_DEGRADED" /\ \E ch \in waived : record.why[ch] = o)
WhyNever_absent          == WhyNever("absent")
WhyNever_unperformable   == WhyNever("unperformable")
WhyNever_invalid         == WhyNever("invalid")
WhyNever_anchor_late     == WhyNever("anchor_late")
WhyNever_names_other_key == WhyNever("names_other_key")
WhyNever_would_pass      == WhyNever("would_pass")

UnverifiableViaAbsentUnreachable ==
  ~(V /\ verdict = "UNVERIFIABLE" /\ \E ch \in Channels \ waived : Observe(ch) = "absent")
InvalidViaConflictUnreachable ==
  ~(V /\ verdict = "INVALID" /\ \E ch \in Channels \ waived : Observe(ch) = "names_other_key")

(* The state on which the two registered readings diverge (PROBE.md Q3):  *)
(* VALID_DEGRADED while a WAIVED evidence's check would have failed.       *)
DegradedWaivedFailUnreachable ==
  ~(V /\ verdict = "VALID_DEGRADED" /\ \E ch \in waived : ChanStatus(ch) = "fail")

(* ADDED 2026-09-06 (later still; PROBE.md post-run note 3 item 2, prediction *)
(* registered there before run 5): the OTHER state on which the two readings *)
(* diverge. The A3.2-literal variant returns INVALID on any failing channel, *)
(* waived or not, so it also differs from the P4 join where P4 says          *)
(* UNVERIFIABLE (a waived channel fails while a required one is              *)
(* unperformable). Q3's "exactly the set {VALID_DEGRADED /\ ...}" was false; *)
(* the divergence set is {verdict \in {VALID_DEGRADED, UNVERIFIABLE} /\      *)
(* \E waived ch : status fail}. Predicted VIOLATED here, HOLDS in _A32Reading.*)
UnverifiableWaivedFailUnreachable ==
  ~(V /\ verdict = "UNVERIFIABLE" /\ \E ch \in waived : ChanStatus(ch) = "fail")

(* The later-capture attack, as a witness that the correct model must NOT *)
(* violate (it is also inside StrictNeedsAuthorizedKey); listed so the    *)
(* _BrokenAnchorIgnored companion can exhibit exactly this trace.          *)
LaterCaptureStrictUnreachable ==
  ~(V /\ verdict = "VALID_STRICT" /\ mkey \notin Authorized
      /\ compIssue = {} /\ compLater = Channels)

===============================================================================
